# Generated by Django 4.2.5 on 2023-12-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bimg', models.ImageField(upload_to='book_cover')),
                ('bfile', models.FileField(upload_to='pdf_files')),
                ('disc', models.TextField(max_length=500)),
                ('download_count', models.CharField(max_length=100)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['bname'],
            },
        ),
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['catagory_name'],
            },
        ),
    ]
