# Generated by Django 4.2.5 on 2023-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='download_count',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
