# Generated by Django 4.2.5 on 2023-12-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_books_bcatagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
