# Generated by Django 4.2.5 on 2023-12-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bimg', models.ImageField(upload_to='book_cover')),
                ('bfile', models.FileField(upload_to='pdf_files')),
                ('author', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('download_count', models.CharField(default=0, max_length=100)),
                ('uploaded_at', models.CharField(max_length=100)),
                ('disc', models.TextField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catagory')),
            ],
            options={
                'ordering': ['bname'],
            },
        ),
    ]
