# Generated by Django 4.2.5 on 2023-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
